spring:
  application:
    name: ms-casemanagementservice
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: override
    url: override
    username: override
    hikari:
      maximum-pool-size: 20
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
integration:
  arendeexport:
    connectTimeout: 5
    readTimeout: 60
    url: override
  case-data:
    oauth2ClientId: override
    oauth2ClientSecret: override
    oauth2TokenUrl: override
    url: override
  alk-t:
    oauth2ClientId: override
    oauth2ClientSecret: override
    oauth2TokenUrl: override
    url: override
  citizen:
    oauth2ClientId: override
    oauth2ClientSecret: override
    oauth2TokenUrl: override
    url: override
  party:
    oauth2ClientId: override
    oauth2ClientSecret: override
    oauth2TokenUrl: override
    url: override
  fb:
    database: override
    password: override
    url: override
    username: override
  lantmateriet:
    oauth2ClientId: override
    oauth2ClientSecret: override
    oauth2TokenUrl: override
    registerbeteckning:
      url: override
  messaging:
    channel: override
    client-id: override
    client-secret: override
    token: override
    token-uri: override
    url: override
  minutmiljo:
    connectTimeout: 5
    password: override
    readTimeout: 60
    url: override
    username: override
  oep-integrator:
    oauth2ClientId: override
    oauth2ClientSecret: override
    oauth2TokenUrl: override
    url: override
logbook:
  body-filters:
    json-path:
      - key: '$..file'
        value: '[base64]'
      - key: '$..filBuffer'
        value: '[base64]'
    xPath:
      - key: '//filBuffer/text()'
        value: '[binary]'
logger:
  max:
    payload:
      length: 10000
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      arendeexport:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      case-data:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      citizen-mapping:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      fb:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      lantmateriet:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      minutmiljo:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem

