integration:
  arendeexport:
    url: http://localhost:${wiremock.server.port:}/TekisArende/ArendeExportWS.svc
  case-data:
    oauth2ClientId: ${SUNDSVALLS_KOMMUN_CONSUMER_KEY}
    oauth2ClientSecret: ${SUNDSVALLS_KOMMUN_CONSUMER_SECRET}
    oauth2TokenUrl: http://localhost:${wiremock.server.port:}/token
    url: http://localhost:${wiremock.server.port:}/case-data
    namespaces:
      2281:
        - "NAMESPACE_1"
        - "NAMESPACE_2"
      2282:
        - "NAMESPACE_3"
        - "NAMESPACE_4"
  alk-t:
    oauth2ClientId: ${SUNDSVALLS_KOMMUN_CONSUMER_KEY}
    oauth2ClientSecret: ${SUNDSVALLS_KOMMUN_CONSUMER_SECRET}
    oauth2TokenUrl: http://localhost:${wiremock.server.port:}/token
    url: http://localhost:${wiremock.server.port:}/alk-t
  citizen:
    oauth2ClientId: ${SUNDSVALLS_KOMMUN_CONSUMER_KEY}
    oauth2ClientSecret: ${SUNDSVALLS_KOMMUN_CONSUMER_SECRET}
    oauth2TokenUrl: http://localhost:${wiremock.server.port:}/token
    url: http://localhost:${wiremock.server.port:}/citizen
  party:
    oauth2ClientId: ${SUNDSVALLS_KOMMUN_CONSUMER_KEY}
    oauth2ClientSecret: ${SUNDSVALLS_KOMMUN_CONSUMER_SECRET}
    oauth2TokenUrl: http://localhost:${wiremock.server.port:}/token
    url: http://localhost:${wiremock.server.port:}/party
  fb:
    database: test_db
    password: test_pass
    url: http://localhost:${wiremock.server.port:}
    username: test_user
  lantmateriet:
    oauth2ClientId: test_key
    oauth2ClientSecret: test_secret
    oauth2TokenUrl: http://localhost:${wiremock.server.port:}/token
    registerbeteckning:
      url: http://localhost:${wiremock.server.port:}/distribution/produkter/registerbeteckning/v5
  messaging:
    channel: channel
    client-id: test_user
    client-secret: test_pass
    token: token
    token-uri: http://localhost:${wiremock.server.port:}/token
    url: http://localhost:${wiremock.server.port:}/messaging/3.1
  minutmiljo:
    password: test_pass
    url: http://localhost:${wiremock.server.port:}/Ecos2PublicServices/MinutMiljoService.svc
    username: test_user
  minutmiljoV2:
    url: http://localhost:${wiremock.server.port:}/Ecos2PublicServices/MinutMiljoServiceV2.svc
  opene:
    password: password
    url: http://localhost:${wiremock.server.port:}/opene/1.0
    username: username
retry:
  initial-delay: 1
  max-delay: 2
  maxAttempts: 1
spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
