package se.sundsvall.casemanagement.api.model.enums;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import net.minidev.json.annotate.JsonIgnore;

@Schema(example = CaseType.Constants.NYBYGGNAD_ANSOKAN_OM_BYGGLOV_VALUE)
public enum CaseType {
    
    // BYGGR BYGGLOV
    NYBYGGNAD_ANSOKAN_OM_BYGGLOV(Constants.NYBYGGNAD_ANSOKAN_OM_BYGGLOV_VALUE, ArendeslagConstants.BYGGR_ARENDESLAG_NYBYGGNAD_AV),
    NYBYGGNAD_FORHANDSBESKED(Constants.NYBYGGNAD_FORHANDSBESKED_VALUE, ArendeslagConstants.BYGGR_ARENDESLAG_NYBYGGNAD_AV),
    TILLBYGGNAD_ANSOKAN_OM_BYGGLOV(Constants.TILLBYGGNAD_ANSOKAN_OM_BYGGLOV_VALUE, ArendeslagConstants.BYGGR_ARENDESLAG_TILLBYGGNAD_AV),
    
    ANDRING_ANSOKAN_OM_BYGGLOV(Constants.ANDRING_ANSOKAN_OM_BYGGLOV_VALUE),
    // BYGGR STRANDSKYDD
    STRANDSKYDD_NYBYGGNAD(Constants.STRANDSKYDD_NYBYGGNAD_VALUE, ArendeslagConstants.BYGGR_ARENDESLAG_NYBYGGNAD_STRANDSKYDD),
    STRANDSKYDD_ANLAGGANDE(Constants.STRANDSKYDD_ANLAGGANDE_VALUE, ArendeslagConstants.BYGGR_ARENDESLAG_ANLAGGANDE_STRANDSKYDD),
    STRANDSKYDD_ANORDNANDE(Constants.STRANDSKYDD_ANORDNANDE_VALUE, ArendeslagConstants.BYGGR_ARENDESLAG_ANORDNARE_STRANDSKYDD),
    STRANDSKYDD_ANDRAD_ANVANDNING(Constants.STRANDSKYDD_ANDRAD_ANVANDNING_VALUE, ArendeslagConstants.BYGGR_ARENDESLAG_ANDRAD_ANVADNING_STRANDSKYDD),
    //BYGGR OTHER
    ANMALAN_ATTEFALL(Constants.ANMALAN_ATTEFALL_VALUE),
    ANMALAN_ELDSTAD(Constants.ANMALAN_ELDSTAD_VALUE),
    // ECOS
    REGISTRERING_AV_LIVSMEDEL(Constants.REGISTRERING_AV_LIVSMEDEL_VALUE),
    ANMALAN_INSTALLATION_VARMEPUMP(Constants.ANMALAN_INSTALLATION_VARMEPUMP_VALUE),
    ANSOKAN_TILLSTAND_VARMEPUMP(Constants.ANSOKAN_TILLSTAND_VARMEPUMP_VALUE),
    ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP(Constants.ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP_VALUE),
    ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC(Constants.ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC_VALUE),
    ANMALAN_ANDRING_AVLOPPSANLAGGNING(Constants.ANMALAN_ANDRING_AVLOPPSANLAGGNING_VALUE),
    ANMALAN_ANDRING_AVLOPPSANORDNING(Constants.ANMALAN_ANDRING_AVLOPPSANORDNING_VALUE),
    ANMALAN_HALSOSKYDDSVERKSAMHET(Constants.ANMALAN_HALSOSKYDDSVERKSAMHET_VALUE),
    UPPDATERING_RISKKLASSNING(Constants.UPPDATERING_RISKKLASSNING_VALUE),
    //OTHER
    PARKING_PERMIT(Constants.PARKING_PERMIT_VALUE),
    PARKING_PERMIT_RENEWAL(Constants.PARKING_PERMIT_RENEWAL_VALUE),
    LOST_PARKING_PERMIT(Constants.LOST_PARKING_PERMIT_VALUE);
    
    @Getter
    private final String text;
    @Getter
    @JsonIgnore
    private final String arendeslag;
    
    CaseType(String text) {
        this.text = text;
        this.arendeslag = null;
    }
    
    CaseType(String text, String arendeslag) {
        this.arendeslag = arendeslag;
        this.text = text;
    }
    
    public static class Constants {
        public static final String TILLBYGGNAD_ANSOKAN_OM_BYGGLOV_VALUE = "TILLBYGGNAD_ANSOKAN_OM_BYGGLOV";
        public static final String ANDRING_ANSOKAN_OM_BYGGLOV_VALUE = "ANDRING_ANSOKAN_OM_BYGGLOV";
        
        public static final String STRANDSKYDD_NYBYGGNAD_VALUE = "STRANDSKYDD_NYBYGGNAD";
        public static final String STRANDSKYDD_ANDRAD_ANVANDNING_VALUE = "STRANDSKYDD_ANDRAD_ANVANDNING";
        public static final String STRANDSKYDD_ANORDNANDE_VALUE = "STRANDSKYDD_ANORDNANDE";
        public static final String STRANDSKYDD_ANLAGGANDE_VALUE = "STRANDSKYDD_ANLAGGANDE";
        
        public static final String ANMALAN_ELDSTAD_VALUE = "ANMALAN_ELDSTAD";
        
        public static final String NYBYGGNAD_FORHANDSBESKED_VALUE = "NYBYGGNAD_FORHANDSBESKED";
        public static final String NYBYGGNAD_ANSOKAN_OM_BYGGLOV_VALUE = "NYBYGGNAD_ANSOKAN_OM_BYGGLOV";
        public static final String ANMALAN_ATTEFALL_VALUE = "ANMALAN_ATTEFALL";
        public static final String REGISTRERING_AV_LIVSMEDEL_VALUE = "REGISTRERING_AV_LIVSMEDEL";
        public static final String ANMALAN_INSTALLATION_VARMEPUMP_VALUE = "ANMALAN_INSTALLATION_VARMEPUMP";
        public static final String ANSOKAN_TILLSTAND_VARMEPUMP_VALUE = "ANSOKAN_TILLSTAND_VARMEPUMP";
        public static final String ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC_VALUE = "ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC";
        public static final String ANMALAN_ANDRING_AVLOPPSANLAGGNING_VALUE = "ANMALAN_ANDRING_AVLOPPSANLAGGNING";
        public static final String ANMALAN_ANDRING_AVLOPPSANORDNING_VALUE = "ANMALAN_ANDRING_AVLOPPSANORDNING";
        public static final String ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP_VALUE = "ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP";
        public static final String ANMALAN_HALSOSKYDDSVERKSAMHET_VALUE = "ANMALAN_HALSOSKYDDSVERKSAMHET";
        public static final String PARKING_PERMIT_VALUE = "PARKING_PERMIT";
        public static final String PARKING_PERMIT_RENEWAL_VALUE = "PARKING_PERMIT_RENEWAL";
        public static final String LOST_PARKING_PERMIT_VALUE = "LOST_PARKING_PERMIT";
        public static final String UPPDATERING_RISKKLASSNING_VALUE = "UPPDATERING_RISKKLASSNING";
        
        private Constants() {
        }
    }
    
    public static class ArendeslagConstants {
        //BYGGLOV
        public static final String BYGGR_ARENDESLAG_NYBYGGNAD_AV = "A";
        public static final String BYGGR_ARENDESLAG_TILLBYGGNAD_AV = "B";
        //STRANDSKYDD
        public static final String BYGGR_ARENDESLAG_ANDRAD_ANVADNING_STRANDSKYDD = "ÄNDR";
        public static final String BYGGR_ARENDESLAG_ANORDNARE_STRANDSKYDD = "AO";
        public static final String BYGGR_ARENDESLAG_ANLAGGANDE_STRANDSKYDD = "A1";
        public static final String BYGGR_ARENDESLAG_NYBYGGNAD_STRANDSKYDD = "NYB";
    }
}
