package se.sundsvall.casemanagement.api.model.enums;


import static se.sundsvall.casemanagement.api.model.enums.CaseType.Value.NYBYGGNAD_ANSOKAN_OM_BYGGLOV;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;

@Schema(example = NYBYGGNAD_ANSOKAN_OM_BYGGLOV)
public enum CaseType {
    
    // ===================  Byggr  ===================
    
    // BYGGR BYGGLOV
    NYBYGGNAD_ANSOKAN_OM_BYGGLOV(Value.NYBYGGNAD_ANSOKAN_OM_BYGGLOV),
    TILLBYGGNAD_ANSOKAN_OM_BYGGLOV(Value.TILLBYGGNAD_ANSOKAN_OM_BYGGLOV),
    UPPSATTANDE_SKYLT(Value.UPPSATTANDE_SKYLT),
    ANDRING_ANSOKAN_OM_BYGGLOV(Value.ANDRING_ANSOKAN_OM_BYGGLOV),
    
    NYBYGGNAD_FORHANDSBESKED(Value.NYBYGGNAD_FORHANDSBESKED),
    
    // BYGGR STRANDSKYDD
    STRANDSKYDD_NYBYGGNAD(Value.STRANDSKYDD_NYBYGGNAD),
    STRANDSKYDD_ANLAGGANDE(Value.STRANDSKYDD_ANLAGGANDE),
    STRANDSKYDD_ANORDNANDE(Value.STRANDSKYDD_ANORDNANDE),
    STRANDSKYDD_ANDRAD_ANVANDNING(Value.STRANDSKYDD_ANDRAD_ANVANDNING),
    
    //BYGGR OTHER
    ANMALAN_ATTEFALL(Value.ANMALAN_ATTEFALL),
    ANMALAN_ELDSTAD(Value.ANMALAN_ELDSTAD),
    
    // ===================  ECOS  ===================
    REGISTRERING_AV_LIVSMEDEL(Value.REGISTRERING_AV_LIVSMEDEL),
    ANMALAN_INSTALLATION_VARMEPUMP(Value.ANMALAN_INSTALLATION_VARMEPUMP),
    ANSOKAN_TILLSTAND_VARMEPUMP(Value.ANSOKAN_TILLSTAND_VARMEPUMP),
    ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP(Value.ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP),
    ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC(Value.ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC),
    ANMALAN_ANDRING_AVLOPPSANLAGGNING(Value.ANMALAN_ANDRING_AVLOPPSANLAGGNING),
    ANMALAN_ANDRING_AVLOPPSANORDNING(Value.ANMALAN_ANDRING_AVLOPPSANORDNING),
    ANMALAN_HALSOSKYDDSVERKSAMHET(Value.ANMALAN_HALSOSKYDDSVERKSAMHET),
    UPPDATERING_RISKKLASSNING(Value.UPPDATERING_RISKKLASSNING),
    
    // ===================  Other  ===================
    PARKING_PERMIT(Value.PARKING_PERMIT),
    PARKING_PERMIT_RENEWAL(Value.PARKING_PERMIT_RENEWAL),
    LOST_PARKING_PERMIT(Value.LOST_PARKING_PERMIT);
    
    @Getter
    private final String value;
    
    CaseType(String value) {
        this.value = value;
    }
    
    public static class Value {
        public static final String UPPSATTANDE_SKYLT = "UPPSATTANDE_SKYLT";
        public static final String TILLBYGGNAD_ANSOKAN_OM_BYGGLOV = "TILLBYGGNAD_ANSOKAN_OM_BYGGLOV";
        public static final String ANDRING_ANSOKAN_OM_BYGGLOV = "ANDRING_ANSOKAN_OM_BYGGLOV";
        public static final String STRANDSKYDD_NYBYGGNAD = "STRANDSKYDD_NYBYGGNAD";
        public static final String STRANDSKYDD_ANDRAD_ANVANDNING = "STRANDSKYDD_ANDRAD_ANVANDNING";
        public static final String STRANDSKYDD_ANORDNANDE = "STRANDSKYDD_ANORDNANDE";
        public static final String STRANDSKYDD_ANLAGGANDE = "STRANDSKYDD_ANLAGGANDE";
        public static final String ANMALAN_ELDSTAD = "ANMALAN_ELDSTAD";
        public static final String NYBYGGNAD_FORHANDSBESKED = "NYBYGGNAD_FORHANDSBESKED";
        public static final String NYBYGGNAD_ANSOKAN_OM_BYGGLOV = "NYBYGGNAD_ANSOKAN_OM_BYGGLOV";
        public static final String ANMALAN_ATTEFALL = "ANMALAN_ATTEFALL";
        public static final String REGISTRERING_AV_LIVSMEDEL = "REGISTRERING_AV_LIVSMEDEL";
        public static final String ANMALAN_INSTALLATION_VARMEPUMP = "ANMALAN_INSTALLATION_VARMEPUMP";
        public static final String ANSOKAN_TILLSTAND_VARMEPUMP = "ANSOKAN_TILLSTAND_VARMEPUMP";
        public static final String ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC = "ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC";
        public static final String ANMALAN_ANDRING_AVLOPPSANLAGGNING = "ANMALAN_ANDRING_AVLOPPSANLAGGNING";
        public static final String ANMALAN_ANDRING_AVLOPPSANORDNING = "ANMALAN_ANDRING_AVLOPPSANORDNING";
        public static final String ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP = "ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP";
        public static final String ANMALAN_HALSOSKYDDSVERKSAMHET = "ANMALAN_HALSOSKYDDSVERKSAMHET";
        public static final String PARKING_PERMIT = "PARKING_PERMIT";
        public static final String PARKING_PERMIT_RENEWAL = "PARKING_PERMIT_RENEWAL";
        public static final String LOST_PARKING_PERMIT = "LOST_PARKING_PERMIT";
        public static final String UPPDATERING_RISKKLASSNING = "UPPDATERING_RISKKLASSNING";
    }
}
